name: Build PXE Boot Artifacts

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Get Latest Release Info
      id: get_latest_release_info
      uses: actions/github-script@v6
      with:
        script: |
          const { data: releases } = await github.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const latestRelease = releases.find(release => !release.draft);
          if (!latestRelease) {
            throw new Error('No published release found.');
          }
          const tagName = latestRelease.tag_name;

          core.setOutput('tag_name', tagName);

    - name: Build PXE Boot Artifacts
      run: |
        ./build.sh

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Upload Kernel and Initrd Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ steps.get_latest_release_info.outputs.tag_name }} ./output/vmlinuz*generic ./output/initrd*generic ./output/root* --clobber

