name: Build PXE Boot Artifacts

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build PXE Boot Artifacts
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pxe-boot-artifacts
        path: ./output

